ScriptError: Use functions with error info for executecommand (#740)
* ScriptError: use functions with error info for executecommand

* GSC: Make the c++ function throw error msg

* Fix balance without overriding whole teams file *gone thankful for h1*

* gsc: remove localize string that does not exist on iw6